---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  selector:
    matchLabels:
      deploy: velero
  strategy: {}
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8085"
        prometheus.io/scrape: "true"
      labels:
        deploy: velero
    spec:
      containers:
        - args:
            - server
            - --features=
            - --log-level
            - debug
          command:
            - /velero
          env:
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LD_LIBRARY_PATH
              value: /plugins
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /credentials/cloud
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: AZURE_CREDENTIALS_FILE
              value: /credentials/cloud
            - name: ALIBABA_CLOUD_CREDENTIALS_FILE
              value: /credentials/cloud
          image: velero/velero:v1.8.1
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
            - containerPort: 8085
              name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - mountPath: /plugins
              name: plugins
            - mountPath: /scratch
              name: scratch
            - mountPath: /credentials
              name: cloud-credentials
      initContainers:
        - image: velero/velero-plugin-for-microsoft-azure:v1.4.1
          imagePullPolicy: IfNotPresent
          name: velero-velero-plugin-for-microsoft-azure
          resources: {}
          volumeMounts:
            - mountPath: /target
              name: plugins
      restartPolicy: Always
      serviceAccountName: velero
      volumes:
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
